In [1]:
import numpy as np

## Eigenvals and Eigenvectors ##

In [4]:
a = np.array([[2, 2, 4], [1, 3, 5], [ 2, 3, 4]])

In [5]:
w, v = np.linalg.eig(a)

In [6]:
print ('Eigenvalues: ', w)

Eigenvalues:  [ 8.80916362  0.92620912 -0.73537273]


In [7]:
print ('Eigenvectors: ', v)

Eigenvectors:  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


## Singular Value Decomposition ## 

In [8]:
u, s, v_t = np.linalg.svd(a)

In [9]:
print(u)

[[-0.52157957  0.51176432 -0.68268004]
 [-0.62993653 -0.7706383  -0.09641875]
 [-0.57544307  0.37975505  0.72432823]]


In [10]:
print(s)

[ 9.30064272  1.06283875  0.60697515]


In [11]:
print(v_t)

[[-0.30363297 -0.50096516 -0.81045724]
 [ 0.95254376 -0.14030457 -0.27013886]
 [-0.02161931  0.85401905 -0.51979233]]


Let's recreate the original matrix from U, S, V

In [16]:
sigma = np.zeros((a.shape[0], a.shape[1]))
sigma

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
sigma[:a.shape[1],:a.shape[1]] = np.diag(s)

In [20]:
sigma

array([[ 9.30064272,  0.        ,  0.        ],
       [ 0.        ,  1.06283875,  0.        ],
       [ 0.        ,  0.        ,  0.60697515]])

In [21]:
np.diag(s)

array([[ 9.30064272,  0.        ,  0.        ],
       [ 0.        ,  1.06283875,  0.        ],
       [ 0.        ,  0.        ,  0.60697515]])

In [25]:
b0 = np.dot(u,sigma)

In [26]:
b = np.dot(b0,v_t)

In [27]:
b

array([[ 2.,  2.,  4.],
       [ 1.,  3.,  5.],
       [ 2.,  3.,  4.]])

## SVD allows us to find the pseuo-inverse as well ##

In [37]:
s_plus = 1.0/s #Find the reciprocals of the eigevalues

In [40]:
sigma_plus = np.zeros(a.shape)

In [42]:
sigma_plus[:a.shape[1],:a.shape[1]] = np.diag(s_plus)

In [78]:
a_pinv0 = np.dot(v_t.T,sigma_plus.T) 
a_pinv0

array([[-0.03264645,  0.89622604, -0.03561811],
       [-0.0538635 , -0.13200927,  1.40700827],
       [-0.08713992, -0.25416731, -0.85636509]])

In [79]:
a_pinv = np.dot(a_pinv0,u.T) 

In [80]:
a_pinv

array([[  5.00000000e-01,  -6.66666667e-01,   3.33333333e-01],
       [ -1.00000000e+00,   2.22044605e-16,   1.00000000e+00],
       [  5.00000000e-01,   3.33333333e-01,  -6.66666667e-01]])

In [64]:
np.linalg.pinv(a)

array([[  5.00000000e-01,  -6.66666667e-01,   3.33333333e-01],
       [ -1.00000000e+00,   2.22044605e-16,   1.00000000e+00],
       [  5.00000000e-01,   3.33333333e-01,  -6.66666667e-01]])

In [81]:
np.linalg.inv(a)

array([[ 0.5       , -0.66666667,  0.33333333],
       [-1.        ,  0.        ,  1.        ],
       [ 0.5       ,  0.33333333, -0.66666667]])